# sinopia 本地的NPM仓库
# 
# node I:\nodejs\sinopia-demo\node_modules\sinopia\lib\cli.js -c I:\nodejs\sinopia-demo\config.yaml
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/rlidwka/sinopia/tree/master/conf
#

# path to a directory with all packages
storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    #max_users: 1000

# a list of other known repositories we can talk to
uplinks:
  npmjs:

# 排在前面的后请求  
    url: https://registry.npmjs.org/
# 排在后面的先请求
    url: http://localhost:9999

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated

  '*':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: sinopia.log, level: info}

#监听的地址
listen:
#localhost
    - http://localhost:4888
#127.0.0.1
    - http://127.0.0.1:6563
#当前IP地址
    - http://192.168.31.212:1234
#局域网上的其他主机通过ip可访问
    - http://0.0.0.0:9876
	
	
